<!--
 * @Descripttion: 
 * @version: 
 * @Author: by_mori
 * @Date: 2021-09-25 16:13:12
 * @LastEditors: by_mori
 * @LastEditTime: 2021-09-25 20:24:37
-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>catch方法与异常穿透</title>
    <script src="./promise.js"></script>
  </head>
  <body>
    <script>
      let p = new Promise((resolve, reject) => {
        setTimeout(() => {
          // reject('ok');
          resolve('ok');
        }, 100);
      });

      p.then()
        .then((value) => {
          console.log(222);
        })
        .then((value) => {
          console.log(333);
        })
        .then((value) => {
          console.log(444);
        })
        .catch((reason) => {
          console.warn(reason);
        });
    </script>
  </body>
</html>
